name = "qrzip"
compatibility_date = "2024-03-20"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB" # i.e. env.DB
database_name = "qrzip-db"
database_id = "559b1d89-9c79-4ad4-bed7-cfc332e6fc20"

[vars]
ADMIN_PASSWORD = "admin1234"
ADMIN_TOKEN = "admin-secret-token-12345"
